## 0 - Imports

In [1]:
#Basic
import pandas as pd
import numpy as np
import json
import math

#Natural Language
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
import re



import string

#Indexing/Scoring
from collections import defaultdict
from rank_bm25 import BM25Okapi

#Embeddings
from sentence_transformers import SentenceTransformer

#Machine Learning
from sklearn.metrics.pairwise import cosine_similarity

## 1 - Data Extraction
- Load JSONs
- See what is available

Use this link https://business.yelp.com/data/resources/open-dataset/
and download the JSON .zip - once downloaded extract it into your repo with the folder within the .gitignore
and then you can run the following code!

In [3]:
#Extracting data - was going to do Phoenix however it is not in the data so we will do all of Arizona

business = pd.read_json('../data/yelp_academic_dataset_business.json', lines=True)
# filtered by Arizona
business = business[business['state'] == 'AZ']
# filter by food/restuarant string
business = business[business['categories'].str.contains('Restaurant | Food',case = False,na=False)
                    &
                    ~business['categories'].str.contains('Drugstore|Convenience|Automotive|Grocery|Store',case = False, na=False)]
#Filter by open
business = business[business['is_open']==1]
#Filter by review count greater than 5
business = business[business['review_count']>5]
business

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
56,txyXRytGjwOXvS8s4sc-WA,Smoothie King,1070 E Tucson Marketplace Blvd,Tucson,AZ,85713,32.186794,-110.954765,3.0,29,1,"{'RestaurantsPriceRange2': '2', 'BusinessParki...","Vitamins & Supplements, Ice Cream & Frozen Yog...","{'Monday': '0:0-0:0', 'Tuesday': '7:0-21:0', '..."
319,f82dhKNiUXsDVPMLqKYiIQ,Sher-e-Punjab,853 East Grant Rd,Tucson,AZ,85719,32.250960,-110.959158,4.0,446,1,"{'RestaurantsAttire': ''casual'', 'BusinessAcc...","Restaurants, Salad, Pakistani, Indian, Cocktai...","{'Tuesday': '16:0-21:0', 'Wednesday': '16:0-21..."
553,adATTqggIQX5xxLDISkFTw,Just Churros,,Tucson,AZ,85705,32.271231,-110.992075,5.0,25,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Food Trucks, Restaurants, Caterers, Event Plan...","{'Monday': '0:0-0:0', 'Friday': '15:0-21:0', '..."
954,2vAqYNN86VWXZiy2E96-TQ,Chick-fil-A,"1303 E University Blvd, Ste 149",Tucson,AZ,85719,32.232445,-110.951699,3.0,13,1,"{'RestaurantsReservations': 'False', 'GoodForK...","Event Planning & Services, Caterers, Fast Food...","{'Monday': '0:0-0:0', 'Tuesday': '10:0-17:0', ..."
995,iNMdSi5bmvGSGeRQiUW4dw,Wendy's,3535 E. Irvington Road,Tucson,AZ,85714,32.163740,-110.916722,2.5,14,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Fast Food, Burgers, Restaurants","{'Monday': '10:0-23:0', 'Tuesday': '10:0-23:0'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149247,zfw03c1jP7sYkIfu1da64w,Panda Express,"9565 E. 22nd Street, SUITE 155",Tucson,AZ,85748,32.206846,-110.788470,2.0,45,1,"{'Ambience': '{'romantic': False, 'intimate': ...","Restaurants, Fast Food, Chinese","{'Monday': '10:30-21:30', 'Tuesday': '10:30-21..."
149436,NHz8uMabvQ2nXk6CddCK4w,McDonald's,3315 N Swan,Tucson,AZ,85712,32.267066,-110.893169,2.5,20,1,"{'RestaurantsAttire': ''casual'', 'Restaurants...","Fast Food, Burgers, Restaurants, Coffee & Tea,...","{'Monday': '5:0-23:0', 'Tuesday': '5:0-23:0', ..."
150000,aGOXuqO6yhN66tLYI61Thg,Jack in the Box,4450 1st Ave,Tucson,AZ,85719,32.287556,-110.960460,4.5,13,1,"{'DriveThru': 'True', 'Caters': 'False', 'Bike...","Tacos, American (Traditional), Fast Food, Mexi...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
150127,K_kRU8j8th6yBeLbI94pJQ,Starbucks,555 E Grant Rd,Tucson,AZ,85705,32.251672,-110.962574,3.5,9,1,"{'RestaurantsTakeOut': 'True', 'BusinessParkin...","Coffee & Tea, Food","{'Monday': '6:0-19:0', 'Tuesday': '6:0-19:0', ..."
150328,1jx1sfgjgVg0nM6n3p0xWA,Savaya Coffee Market,11177 N Oracle Rd,Oro Valley,AZ,85737,32.409552,-110.943073,4.5,41,1,"{'BusinessParking': '{'garage': False, 'street...","Specialty Food, Food, Coffee & Tea, Coffee Roa...","{'Monday': '0:0-0:0', 'Tuesday': '6:0-14:0', '..."

In [4]:
#Gather IDs
ids = business['business_id'].to_list()
# Append reviews safely
reviews = []
with open('../data/yelp_academic_dataset_review.json','r', encoding = 'utf-8') as f:
    for line in f:
        review = json.loads(line)
        if review['business_id'] in ids:
            reviews.append(review)

rev_df = pd.DataFrame(reviews)
rev_df

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,onlgwy5qGDEzddsrnIvtWg,pYXeL0RCqus2IfhthYCOyA,W7NxQw8UYFR0HLPrI08tvw,4.0,0,0,0,Don't know what it is but If my tummy's feelin...,2012-02-01 14:21:25
1,mRnYZes0nj4sr8DsE_gWMQ,FuTJWFYm4UKqewaosss1KA,fgTOJRkc703E4XRdcr5zRA,3.0,3,0,0,I've come from Cali where boba is very common ...,2016-01-30 01:59:11
2,f7fAYGJpd4gZAoJxuJcciw,LpZfJekvMo5S61UBAmuyHw,cXAKeC-EgVChIxhS7fscmw,5.0,2,0,0,The food at Ghini's is just delicious. Everyth...,2011-05-27 15:44:29
3,b0AI6U9CCWpFKI3iPLYiow,_l0csyXqNIcb3vG-1qR8DQ,UCMSWPqzXjd7QHq7v8PJjQ,4.0,0,0,0,I really like Prep & Pastry - we have been twi...,2017-09-20 18:19:33
4,Zssrl36KBW-QMHsa8G9a_w,zcYZgNeJHpKCSBRwh6WskQ,SbdL-8NSmTWgSwdGZBa7WQ,5.0,0,0,0,Another five-star dining review! Fresco serve...,2015-02-24 04:27:38
...,...,...,...,...,...,...,...,...,...
78857,VkXr54yJMN4Qu4dRznAN8Q,4jEdEPDNAAa3aS7rYhQ60w,MK0OMY_u9unl8xSqjPLtMw,5.0,3,0,0,"ALWAYS love this place! And it's always busy, ...",2020-01-17 20:58:05
78858,JA8GCU3glb6TQRExleWjHg,Iq-9jCp219AEcbtjy-ZyNQ,tBWjMqUc0yP5lRElCfDaKg,5.0,1,0,1,"Great pizza, awesome choices of beers, pet fri...",2016-07-25 01:08:01
78859,PMgEv05rnLIJZlpGc4IHvQ,CDUkT2tD6y3gSfivf3Beyw,EhFJgjgn9Kzo_gu03DVkRg,3.0,1,0,0,Not my favorite dessert place. You don't get m...,2018-02-05 17:27:07
78860,jacDcaIWSPdZq2bDq1GD_g,Y-mwrjOx29pnJX0MCBb2Yg,9VRmMY9vGhGKGz9hiGoEUw,1.0,0,0,0,If I could leave no stars I would. I understan...,2021-11-28 14:23:39
78861,YGUyDcnAxZsUAjlK3QF99g,Qa5MBgb7Xyrr9Pg5bD4taQ,jh8j-DWqgWkbRe_a2XtKFQ,5.0,0,0,1,My secret to finding good food often starts by...,2021-11-28 22:24:05

In [5]:
#Concatenate maximum 20 reviews for each unique business_id
group_rev = (rev_df.groupby('business_id')['text'].apply(lambda x: " ".join(x[:20])).reset_index())
group_rev

                business_id                                               text
0    -1w9JMktu9oWTXwNqtZQoA  I was in Tuscan from Baltimore md . I stumbled...
1    -3-6BB10tIWNKGEF0Es2BA  We will absolutely be coming back here! The ch...
2    -7cNgs6N105MDlLjOudObg  I'm a regular here for sure. Fresh ingredients...
3    -Ah16__ceG91aXtrbkhkxQ  Yummy cakes! Always fresh and they taste great...
4    -B6fyJ8PoAMr_mH5VGaPjA  Best Bacon wrapped burritos in Town, come in e...
..                      ...                                                ...
969  zbhID412Pg3zXd_t3mswpg  Finally! A last minute BB fix before you leave...
970  zfw03c1jP7sYkIfu1da64w  First time eating at this location. The inside...
971  zgClnCzcLl1gzUeKFaJAhg  The food was good the service was slow but lat...
972  zkrEIgrkGylMek2-dUZgZg  I tried Popeyes again 3 months after the 1st r...
973  zwrgCMuZyFX46mL3piDyjg  Amazing food.... This time I had the nicoise, ...

[974 rows x 2 columns]

In [6]:
# Merge business data to get documents
docs = business.merge(group_rev, on='business_id')

docs['document'] = (
    'Name: ' + docs['name'] + '\n' +
    'Categories: ' + docs['categories'] + '\n' +
    'Ratings: ' + docs['stars'].astype(str) + '\n' +
    'Reviews: ' + docs['text'].fillna('')

)
docs['document']

0      Name: Smoothie King\nCategories: Vitamins & Su...
1      Name: Sher-e-Punjab\nCategories: Restaurants, ...
2      Name: Just Churros\nCategories: Food Trucks, R...
3      Name: Chick-fil-A\nCategories: Event Planning ...
4      Name: Wendy's\nCategories: Fast Food, Burgers,...
                             ...
969    Name: Panda Express\nCategories: Restaurants, ...
970    Name: McDonald's\nCategories: Fast Food, Burge...
971    Name: Jack in the Box\nCategories: Tacos, Amer...
972    Name: Starbucks\nCategories: Coffee & Tea, Foo...
973    Name: Savaya Coffee Market\nCategories: Specia...
Name: document, Length: 974, dtype: object

In [7]:
# Save corpus of documents (restaurant data) as .pkl - no need to run Step 1: again after this
# From now on use .pkl
docs['document'].to_pickle('../data/arizona_restuarant_corpus.pkl')

## 2 - Preprocessing
- lowercase
- tokenization
- stemming (removed for now)
- stopword removal

In [2]:
documents = pd.read_pickle('../data/arizona_restuarant_corpus.pkl')
documents

0      Name: Smoothie King\nCategories: Vitamins & Su...
1      Name: Sher-e-Punjab\nCategories: Restaurants, ...
2      Name: Just Churros\nCategories: Food Trucks, R...
3      Name: Chick-fil-A\nCategories: Event Planning ...
4      Name: Wendy's\nCategories: Fast Food, Burgers,...
                             ...
969    Name: Panda Express\nCategories: Restaurants, ...
970    Name: McDonald's\nCategories: Fast Food, Burge...
971    Name: Jack in the Box\nCategories: Tacos, Amer...
972    Name: Starbucks\nCategories: Coffee & Tea, Foo...
973    Name: Savaya Coffee Market\nCategories: Specia...
Name: document, Length: 974, dtype: object

In [ ]:
#Preprocess - appears to work better for vocab list
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

def preprocess(text):
    tokens = text.lower().split() #lower case all
    tokens = [x for x in tokens if x not in stop_words and x not in string.punctuation] #no stop words or punctuations
    # tokens = [stemmer.stem(x) for x in tokens] #stemming
    return tokens

In [ ]:
#Preprocess V2 - appears to work better for cleaning up queries to be meaningful
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocessv2(text):
    #lowercase text
    text = text.lower()

    # tokenize words
    tokens = re.findall(r"\b[a-z]+\b",text)

    #tokenization
    # tokens = text.split()

    #removing stop words
    tokens = [x for x in tokens if x not in stop_words]

    # lemmatize 
    tokens = [lemmatizer.lemmatize(x) for x in tokens]
    return tokens

In [120]:
# Apply to documents
tokens0 = [preprocess(doc) for doc in documents]
tokens = [preprocessv2(doc) for doc in documents]

print(f'Original: {tokens0[0][:5]} --> New: {tokens0[0][:5]}')

Original: ['name:', 'smoothie', 'king', 'categories:', 'vitamins'] --> New: ['name:', 'smoothie', 'king', 'categories:', 'vitamins']

## 3 - Indexing | Scoring (Initial Test)
- Create the Inverted Index 
- TF-IDF testing
- BM25 testing
- GOAL: Make the inverted index and just check and see how scoring works

In [121]:
# INVERTED INDEX

invert_index = defaultdict(dict)

for id, token in enumerate(tokens):
    for x in token:
        invert_index[x][id] = invert_index[x].get(id,0)+1

#example 

print(invert_index['taco'])

{8: 3, 9: 26, 12: 1, 24: 3, 32: 26, 35: 4, 36: 18, 38: 1, 40: 1, 41: 1, 43: 19, 73: 2, 76: 2, 79: 1, 83: 26, 90: 19, 96: 19, 99: 1, 105: 4, 106: 4, 110: 2, 111: 19, 112: 6, 115: 1, 116: 1, 119: 3, 120: 4, 126: 18, 127: 5, 131: 3, 141: 6, 146: 4, 151: 6, 154: 8, 158: 1, 172: 7, 179: 25, 180: 4, 181: 27, 187: 4, 189: 14, 190: 2, 191: 2, 201: 1, 218: 1, 219: 2, 224: 2, 228: 2, 229: 2, 231: 1, 234: 1, 243: 3, 248: 1, 251: 1, 263: 4, 264: 23, 266: 1, 270: 13, 272: 2, 278: 13, 284: 22, 285: 4, 287: 5, 300: 6, 305: 19, 312: 26, 320: 1, 323: 4, 326: 9, 330: 1, 345: 1, 353: 15, 361: 22, 364: 7, 365: 2, 375: 5, 383: 10, 390: 21, 392: 13, 393: 27, 402: 1, 403: 2, 407: 8, 409: 2, 421: 4, 426: 1, 430: 3, 432: 1, 435: 2, 436: 1, 445: 1, 447: 20, 451: 7, 455: 2, 460: 10, 464: 1, 472: 32, 474: 16, 475: 5, 492: 21, 495: 1, 501: 1, 509: 12, 521: 43, 522: 1, 526: 1, 530: 2, 534: 31, 535: 1, 549: 16, 552: 1, 554: 1, 556: 2, 561: 8, 567: 15, 570: 6, 571: 3, 579: 2, 591: 2, 592: 1, 595: 2, 597: 7, 628: 10, 630: 1, 633: 2, 634: 16, 641: 1, 647: 15, 651: 1, 655: 1, 660: 2, 663: 1, 668: 13, 686: 1, 688: 8, 691: 21, 699: 5, 703: 26, 704: 30, 705: 3, 709: 11, 712: 11, 715: 30, 716: 1, 719: 1, 722: 1, 728: 6, 729: 38, 730: 5, 746: 1, 747: 9, 751: 10, 752: 1, 754: 2, 760: 3, 767: 1, 770: 6, 772: 40, 775: 3, 790: 1, 799: 4, 801: 2, 803: 1, 804: 6, 811: 12, 814: 2, 820: 7, 823: 1, 824: 1, 830: 29, 831: 18, 834: 17, 835: 7, 839: 6, 840: 5, 842: 43, 847: 2, 852: 41, 859: 17, 864: 4, 870: 5, 874: 1, 880: 6, 883: 26, 887: 31, 897: 6, 902: 1, 905: 2, 906: 1, 907: 5, 909: 5, 910: 4, 911: 2, 915: 4, 918: 11, 932: 1, 933: 1, 940: 2, 950: 1, 956: 1, 957: 19, 959: 4, 961: 1, 967: 20, 971: 5}

In [122]:
# Basic TF-IDF

# N - total # docs
# df - number of docs with term
# idf - log(N/df)


N = len(tokens)

def tfidf(term):
    df = len(invert_index[term])
    return math.log(N/df)


tfidf_score = tfidf('taco')

print(tfidf_score)


#BUILD IDF DICTIONARY
idf = {}
for term in invert_index:
    df = len(invert_index[term])
    idf[term] = math.log(N/df)

#maybe add l2 normalization to make it 0-1 scale

1.5584013245041268

In [126]:
# BM25 Implementation
bm25 = BM25Okapi(tokens)

query = preprocessv2('best tacos')

scores = bm25.get_scores(query)

print('Before Ranking')
print(scores[:5])
ranked_docs = np.argsort(scores)[::-1]
print(f'\nAfter Ranking\n{ranked_docs[:5]}')

Before Ranking
[2.39108109 2.66423091 2.63177683 1.54282944 1.65668543]

After Ranking
[472 715  36 859 709]

In [127]:
#TF-IDF scoring logic
N = len(tokens)

def tfidf_scoring(query):
    scores = [0] * N

    for x in query:
        if x in invert_index:
            for id,tf in invert_index[x].items():
                # scores[id]+=tf*idf[x] #basic
                scores[id] += (tf / len(tokens[id])) *idf[term] #length normalization - way more similar to BM25

    return scores

In [128]:
#Compare Scores
#TF-IDF
tf_scores = tfidf_scoring(query)

#BM25
bm25_scores = bm25.get_scores(query)

def top_results(scores,x=5):
    return np.argsort(scores)[::-1][:x] #top 5 results

tf_top = top_results(tf_scores)
bm_top = top_results(bm25_scores)

print(f'TF-IDF Top Results: ')
for rank,id in enumerate(tf_top,1):
    print(f'{rank} -> (Document: {id}) -> Score: {tf_scores[id]:.2f}')
    print('  ', tokens[id])

print('\nBM25 Top Results: ')
for rank, id in enumerate(bm_top,1):
    print(f'{rank} -> (Document: {id}) -> Score: {bm25_scores[id]:.2f}')
    print('   ', tokens[id])

TF-IDF Top Results:
1 -> (Document: 709) -> Score: 0.48
   ['name', 'taco', 'rico', 'category', 'food', 'truck', 'food', 'taco', 'restaurant', 'fast', 'food', 'mexican', 'rating', 'review', 'absolutely', 'delicious', 'best', 'mexican', 'truck', 'tucson', 'glad', 'located', 'ina', 'driving', 'south', 'sometimes', 'drag', 'waste', 'time', 'writing', 'review', 'going', 'show', 'day', 'write', 'many', 'review', 'deleted', 'well', 'sure', 'owner', 'business', 'since', 'gave', 'star', 'review', 'assume', 'yelp', 'great', 'taco', 'taco', 'truck', 'specializes', 'taco', 'ordered', 'chicken', 'carne', 'asada', 'steak', 'taco', 'came', 'sliced', 'radish', 'grilled', 'onion', 'cilantro', 'sauce', 'tried', 'pastor', 'asada', 'cabeza', 'taco', 'delicious', 'tortilla', 'excellent', 'meat', 'fresh', 'moist', 'served', 'radish', 'cucumber', 'onion', 'side', 'plus', 'traveled', 'oro', 'valley', 'say', 'worth', 'trip', 'back', 'soon', 'food', 'truck', 'actually', 'really', 'good', 'tried', 'asada', 'cabeza', 'pollo', 'pastor', 'taco', 'excellent', 'pollo', 'super', 'moist', 'cabeza', 'greasy', 'wife', 'carne', 'asada', 'connoisseur', 'liked', 'asada', 'really', 'tell', 'something', 'new', 'cali', 'probably', 'liked', 'forget', 'add', 'cheese', 'salsa', 'homemade', 'bomb', 'super', 'good', 'food', 'maybe', 'best', 'town', 'nice', 'people', 'fresh', 'clean', 'food', 'homemade', 'horchata', 'outstanding', 'hopefully', 'move', 'closer', 'town', 'would', 'time', 'first', 'time', 'taco', 'truck', 'glad', 'stopped', 'way', 'home', 'probably', 'top', 'best', 'taco', 'tucson', 'come', 'carne', 'asada', 'al', 'pastor', 'also', 'red', 'chili', 'hot', 'oil', 'sauce', 'amazing', 'lightweight', 'beware', 'hot', 'dang', 'flavorful', 'definitely', 'gonna', 'picking', 'taco', 'side', 'town', 'skimp', 'meat', 'either', 'side', 'salsa', 'place', 'legit', 'go', 'support', 'great', 'local', 'food', 'truck', 'especially', 'awesome', 'price']
2 -> (Document: 472) -> Score: 0.44
   ['name', 'taqueria', 'rosita', 'category', 'food', 'truck', 'food', 'rating', 'review', 'best', 'carne', 'asada', 'town', 'best', 'salsa', 'town', 'best', 'cabeza', 'town', 'even', 'need', 'teeth', 'chew', 'tender', 'sad', 'discontinued', 'adobada', 'also', 'best', 'town', 'rafa', 'josefina', 'always', 'cheerful', 'gracious', 'host', 'spot', 'epitome', 'elegant', 'street', 'fair', 'eating', 'close', 'year', 'find', 'better', 'taco', 'tucson', 'easily', 'one', 'best', 'taco', 'truck', 'tucson', 'eat', 'least', 'twice', 'week', 'never', 'get', 'sick', 'carne', 'asada', 'taco', 'definitely', 'par', 'aqui', 'con', 'el', 'nene', 'birria', 'cabesa', 'also', 'tasty', 'wednesday', 'taco', 'day', 'prepared', 'wait', 'awhile', 'come', 'day', 'personally', 'think', 'worth', 'spend', 'extra', 'cent', 'avoid', 'rush', 'coming', 'non', 'wednesday', 'still', 'pretty', 'cheap', 'miss', 'gem', 'awesome', 'food', 'truck', 'far', 'best', 'carne', 'asada', 'burrito', 'tucson', 'meat', 'flavorful', 'tender', 'salsa', 'good', 'back', 'favorite', 'taco', 'caramelos', 'burro', 'consistent', 'quality', 'always', 'cooked', 'wait', 'best', 'food', 'tucson', 'love', 'place', 'staff', 'friendly', 'food', 'delicious', 'eat', 'keep', 'mind', 'dirt', 'lot', 'going', 'clean', 'always', 'get', 'mine', 'go', 'since', 'work', 'close', 'accept', 'cash', 'problem', 'know', 'ahead', 'time', 'carne', 'asada', 'trimmed', 'nicely', 'price', 'portion', 'good', 'oh', 'park', 'spot', 'early', 'prep', 'open', 'lunch', 'highly', 'recommend', 'place', 'carne', 'asada', 'taco', 'best', 'food', 'truck', 'delicious', 'guacamole', 'salsa', 'perfect', 'may', 'wait', 'bit', 'hey', 'line', 'usually', 'good', 'sign', 'worth', 'wait', 'one', 'great', 'mexican', 'food', 'truck', 'gem', 'tucson', 'basic', 'menu', 'food', 'good', 'usually', 'get', 'burrito', 'taco', 'tortas', 'carmelos', 'asada', 'birria', 'cabeza', 'pollo', 'adobado', 'highly', 'reccomend', 'truck', 'looking', 'authentic', 'tucson', 'food', 'truck', 'experience', 'gang', 'work', 'really', 'love', 'taco', 'truck', 'taqueria', 'great', 'taco', 'great', 'burrito', 'cabeza', 'carne', 'asada', 'pollo', 'several', 'table', 'available', 'shade', 'tree', 'get', 'go', 'taco', 'easily', 'best', 'town', 'rosita', 'every', 'dollar', 'spend', 'towards', 'authentic', 'full', 'flavorful', 'taco', 'b', 'real', 'tucson', 'gem', 'inhale', 'taco', 'exhale', 'negativity', 'namaste', 'mi', 'amigo', 'taco', 'truck', 'lover', 'really', 'care', 'sketchy', 'place', 'look', 'try', 'heck', 'eaten', 'taco', 'stand', 'people', 'front', 'yard', 'puerto', 'penasco', 'yeah', 'bring', 'taco', 'taqueria', 'rosita', 'nothing', 'fancy', 'tent', 'truck', 'dirt', 'lot', 'kind', 'nestled', 'back', 'tree', 'bit', 'along', 'valencia', 'carne', 'asada', 'taco', 'lord', 'taco', 'bout', 'awesome', 'recent', 'visit', 'meat', 'perfection', 'gristle', 'little', 'fatty', 'piece', 'ton', 'flavor', 'actually', 'charred', 'grill', 'bit', 'give', 'flavor', 'taco', 'place', 'missing', 'watch', 'red', 'salsa', 'spicy', 'delicious', 'spicy', 'favor', 'stop', 'carne', 'asada', 'taco', 'remember', 'bring', 'cash', 'cuz', 'rosita', 'take', 'card', 'jefe', 'wow', 'delicious', 'place', 'probably', 'best', 'mexican', 'food', 'since', 'coming', 'arizona', 'carne', 'asada', 'taco', 'fresh', 'vibrant', 'tasty', 'offer', 'great', 'pico', 'de', 'gillo', 'guac', 'hot', 'sauce', 'meat', 'option', 'available', 'would', 'eat', 'anything', 'taco', 'first', 'time', 'yesterday', 'delicious', 'first', 'time', 'fell', 'taco', 'tucson', 'make', 'want', 'go', 'back', 'thank', 'best', 'taco', 'tucson', 'live', 'vail', 'happy', 'made', 'minute', 'drive', 'little', 'roach', 'coach', 'husband', 'pleased', 'offered', 'choice', 'corn', 'flour', 'tortilla', 'prefer', 'flour', 'found', 'tortilla', 'delicious', 'thin', 'seemingly', 'homemade', 'u', 'tried', 'pollo', 'asada', 'birria', 'good', 'asada', 'particularly', 'delicious', 'pico', 'great', 'enjoyed', 'sauce', 'ordered', 'go', 'order', 'bring', 'home', 'son', 'waited', 'nearly', 'finished', 'meal', 'prepare', 'extremely', 'considerate', 'would', 'convenient', 'accept', 'card', 'yes', 'keep', 'line', 'moving', 'faster', 'taco', 'cash', 'totally', 'worth', 'gentleman', 'inside', 'truck', 'kind', 'make', 'terrific', 'food', 'already', 'dreaming', 'next', 'visit', 'love', 'corn', 'tortilla', 'thin', 'soft', 'flavorful', 'packed', 'favorite', 'meat', 'fresh', 'ingredient', 'service', 'fast', 'friendly', 'fooled', 'location', 'appearance', 'lone', 'truck', 'gravel', 'lot', 'nice', 'shady', 'spacious', 'outdoor', 'eating', 'area', 'park', 'like', 'setting', 'clean', 'table', 'back', 'great', 'choice', 'tucson', 'taco', 'truck', 'experience', 'sweet', 'people', 'working', 'food', 'taste', 'great', 'feeling', 'sitting', 'foldout', 'table', 'couple', 'tree', 'cracking', 'open', 'bottle', 'coca', 'cola', 'hard', 'beat', 'best', 'bang', 'buck', 'taco', 'tucson', 'pure', 'joy', 'wished', 'open', 'longer', 'think', 'close', 'come', 'lunch', 'almost', 'daily', 'never', 'ever', 'disappointed', 'outstanding', 'street', 'taco', 'exactly', 'looking', 'street', 'truck', 'food', 'super', 'friendly', 'helpful', 'suggesting', 'topping', 'added', 'bonus', 'small', 'entertainer', 'made', 'visit', 'hand', 'one', 'best', 'taco', 'tucson', 'simple', 'taco', 'truck', 'outdoor', 'seating', 'food', 'packed', 'amazing', 'flavor', 'plus', 'price', 'right', 'tried', 'meat', 'far', 'taco', 'exception', 'chicharron', 'cooked', 'seasoned', 'perfectly', 'sure', 'try', 'caramelos', 'also', 'got', 'carne', 'asada', 'caramelos', 'divine', 'cheesy', 'cooked', 'perfection', 'outside', 'bit', 'crunchy', 'crisp', 'provided', 'u', 'pico', 'de', 'gallo', 'salsa', 'red', 'one', 'spiciest', 'add', 'great', 'kick', 'highly', 'recommend', 'place', 'thank', 'open', 'covid', 'time', 'definitely', 'back', 'recommending', 'spot', 'fellow', 'foodie', 'seriously', 'best', 'taco', 'ever', 'hearty', 'portion', 'meat', 'perfect', 'seasoning', 'price', 'great', 'plus', 'ordered', 'limonade', 'found', 'made', 'bottled', 'tucson', 'limonade', 'honestly', 'best', 'ever', 'careful', 'lot', 'sugar', 'damn', 'worth', 'new', 'go', 'spot', 'rest', 'time', 'live', 'added', 'bonus', 'nice', 'lady', 'patient', 'answered', 'question', 'also', 'sell', 'birria', 'juice', 'bigger', 'quart', 'take', 'home', 'perfect', 'hole', 'wall', 'decided', 'review', 'since', 'place', 'much', 'review', 'photo', 'delicious', 'tucson', 'finding', 'good', 'taco', 'mission', 'place', 'road', 'hotel', 'convenient', 'tried', 'asada', 'cabeza', 'divine', 'serve', 'onion', 'cilantro', 'cabbage', 'add', 'guacamole', 'salsa', 'salsa', 'bit', 'spicy', 'stay', 'away', 'good', 'opinion', 'guacamole', 'runny', 'side', 'tasty', 'well', 'also', 'give', 'option', 'pico', 'de', 'gallo', 'fresh', 'definitely', 'worth', 'try']
3 -> (Document: 715) -> Score: 0.41
   ['name', 'taco', 'de', 'cabeza', 'category', 'food', 'food', 'truck', 'restaurant', 'mexican', 'rating', 'review', 'complains', 'food', 'excellent', 'complain', 'place', 'look', 'never', 'clean', 'yard', 'look', 'ugly', 'place', 'extraordinary', 'best', 'cabeza', 'taco', 'tucson', 'hand', 'go', 'usually', 'take', 'taco', 'de', 'cabeza', 'beef', 'head', 'taco', 'bichi', 'beef', 'stew', 'w', 'onion', 'cilantro', 'coca', 'cola', 'eating', 'taco', 'de', 'cabeza', 'shame', 'drinking', 'mexican', 'coca', 'cola', 'noon', 'fantastic', 'delicious', 'taco', 'broth', 'always', 'order', 'cheek', 'taco', 'broth', 'husband', 'order', 'cabeza', 'tongue', 'taco', 'filling', 'lunch', 'two', 'u', 'never', 'cost', 'best', 'taco', 'tucson', 'come', 'every', 'weekend', 'family', 'recommend', 'one', 'sesos', 'taco', 'order', 'jugo', 'bichi', 'beef', 'stew', 'amazing', 'taco', 'place', 'casual', 'great', 'street', 'taco', 'cash', 'option', 'vegetarian', 'option', 'carnivore', 'definitely', 'try', 'taco', 'best', 'ever', 'go', 'stand', 'grant', 'school', 'week', 'always', 'get', 'cabeza', 'cachete', 'staff', 'helpful', 'kind', 'speak', 'spanish', 'hard', 'communicate', 'sometimes', 'lol', 'definitely', 'recommend', 'first', 'day', 'tucson', 'accidentally', 'went', 'parking', 'lot', 'realized', 'food', 'truck', 'ton', 'white', 'tent', 'seating', 'knew', 'stop', 'try', 'aa', 'part', 'first', 'food', 'tucson', 'menu', 'immediately', 'visible', 'decided', 'order', 'cabeza', 'since', 'seemed', 'specialty', 'based', 'name', 'waitress', 'spoke', 'limited', 'english', 'bit', 'tough', 'u', 'since', 'neither', 'sister', 'speak', 'spanish', 'difficulty', 'asking', 'meat', 'taco', 'came', 'delicious', 'corn', 'tortilla', 'best', 'meat', 'taco', 'super', 'cheap', 'think', 'horchata', 'bottle', 'cost', 'two', 'taco', 'got', 'lolll', 'note', 'outdoor', 'seating', 'since', 'food', 'truck', 'hot', 'hot', 'az', 'definitely', 'sweating', 'quickly', 'car', 'extremely', 'hot', 'without', 'sun', 'shade', 'definitely', 'need', 'go', 'back', 'even', 'daydream', 'taco', 'get', 'munchies', 'got', 'cheek', 'head', 'roof', 'mouth', 'tongue', 'taco', 'little', 'disappointed', 'ran', 'eye', 'lip', 'brain', 'taco', 'great', 'flavor', 'mild', 'side', 'good', 'early', 'day', 'bite', 'price', 'good', 'cash', 'best', 'taco', 'cabezas', 'tucson', 'son', 'make', 'mission', 'sample', 'every', 'beef', 'pork', 'cabezas', 'discover', 'tucson', 'flavor', 'taco', 'cabezas', 'nothing', 'short', 'miracle', 'flavor', 'seved', 'tortilla', 'depth', 'flavor', 'spice', 'without', 'heavy', 'grease', 'sometimes', 'associated', 'particular', 'epicurean', 'delight', 'try', 'broth', 'take', 'home', 'freezer', 'midnight', 'craving', 'adventurous', 'try', 'mixed', 'meat', 'cabezas', 'blend', 'headmeats', 'prepared', 'expertly', 'experience', 'exquisite', 'beef', 'flavor', 'without', 'bizarre', 'texture', 'usually', 'associated', 'head', 'meat', 'true', 'jewel', 'tucson', 'cuisine', 'offer', 'like', 'oh', 'less', 'adventurous', 'offer', 'standard', 'selection', 'expect', 'see', 'mexican', 'food', 'tuck', 'best', 'home', 'style', 'taco', 'missing', 'home', 'would', 'give', 'five', 'star', 'however', 'get', 'different', 'quality', 'depending', 'go', 'overall', 'still', 'great', 'girlfriend', 'really', 'craving', 'taco', 'de', 'cabeza', 'past', 'day', 'finally', 'found', 'place', 'serf', 'good', 'one', 'town', 'basic', 'plastic', 'table', 'tarp', 'covering', 'food', 'truck', 'let', 'fool', 'place', 'know', 'going', 'still', 'get', 'table', 'service', 'waitress', 'take', 'order', 'super', 'super', 'fast', 'like', 'joke', 'fast', 'looking', 'authentic', 'taco', 'place', 'super', 'fast', 'friendly', 'even', 'though', 'super', 'busy', 'taco', 'de', 'cabeza', 'lengua', 'vichi', 'tasted', 'super', 'good', 'bit', 'small', 'order', 'extra', 'ordered', 'taco', 'vichis', 'soda', 'total', 'place', 'super', 'busy', 'weekend', 'prepare', 'wait', 'say', 'enough', 'good', 'thing', 'taco', 'de', 'cabeza', 'guy', 'best', 'cabeza', 'ever', 'eaten', 'arizona', 'even', 'mexico', 'reasonable', 'price', 'great', 'authentic', 'selection', 'cabeza', 'typical', 'mexican', 'food', 'great', 'space', 'eat', 'shade', 'stand', 'staff', 'nice', 'even', 'pasty', 'white', 'gringo', 'speak', 'spanish', 'love', 'amazing', 'mexican', 'food', 'always', 'accommodating', 'ordering', 'time', 'order', 'cabeza', 'go', 'get', 'large', 'stack', 'good', 'quality', 'corn', 'tortilla', 'fairly', 'spicy', 'red', 'citrusy', 'green', 'salsa', 'big', 'bag', 'lime', 'accentuate', 'flavor', 'delicious', 'meat', 'broth', 'cachete', 'cheek', 'taco', 'full', 'unconditional', 'support', 'cannot', 'go', 'wrong', 'never', 'tried', 'cabeza', 'fear', 'strange', 'texture', 'anything', 'worry', 'favor', 'give', 'try', 'two', 'note', 'make', 'writing', 'location', 'yelp', 'located', 'street', 'alaska', 'northeast', 'corner', 'small', 'sign', 'visible', 'road', 'also', 'used', 'take', 'card', 'year', 'ago', 'since', 'stopped', 'back', 'cash', 'situation', 'found', 'place', 'yelp', 'neighborhood', 'thought', 'would', 'give', 'shot', 'disappointed', 'food', 'wonderful', 'ordered', 'slew', 'beef', 'cheek', 'taco', 'recommendation', 'kind', 'folk', 'table', 'next', 'u', 'waitress', 'speak', 'word', 'english', 'printed', 'menu', 'little', 'tough', 'figure', 'taco', 'arrived', 'quickly', 'piping', 'hot', 'texture', 'meat', 'wonderful', 'guy', 'thought', 'food', 'pretty', 'extraordinary', 'spouse', 'thought', 'flavor', 'little', 'strong', 'one', 'complained', 'could', 'smell', 'meat', 'finger', 'afternoon', 'would', 'consider', 'bonus', 'quite', 'fond', 'idea', 'lunch', 'people', 'including', 'couple', 'coca', 'cola', 'quite', 'bargain', 'would', 'give', 'place', 'star', 'food', 'would', 'great', 'made', 'thing', 'little', 'easier', 'u', 'gringo', 'menu', 'card']
4 -> (Document: 83) -> Score: 0.38
   ['name', 'taqueria', 'el', 'cheke', 'category', 'burger', 'food', 'truck', 'street', 'vendor', 'food', 'restaurant', 'mexican', 'rating', 'review', 'los', 'taco', 'estan', 'muy', 'buenos', 'autentico', 'sabor', 'de', 'sonora', 'la', 'barra', 'de', 'salsa', 'muy', 'fresco', 'buena', 'atencion', 'abren', 'hasta', 'tarde', 'little', 'food', 'truck', 'serf', 'taco', 'tortas', 'hot', 'dog', 'flavorful', 'carne', 'asada', 'little', 'dry', 'side', 'hod', 'dog', 'delicious', 'kuddos', 'topping', 'bar', 'best', 'sonoran', 'hot', 'dog', 'northside', 'town', 'everything', 'made', 'fresh', 'delicious', 'recommend', 'doubt', 'mexican', 'food', 'cart', 'fyi', 'hotdog', 'tuesday', 'riquisimos', 'taco', 'bien', 'super', 'recomendados', 'estuvimos', 'todo', 'el', 'grupo', 'de', 'barbershop', 'gracias', 'must', 'start', 'observation', 'none', 'employee', 'mask', 'pandemic', 'going', 'follow', 'common', 'sense', 'heath', 'practice', 'go', 'one', 'competitor', 'food', 'service', 'otherwise', 'good', 'best', 'mexican', 'food', 'tucson', 'near', 'tucson', 'mall', 'sonoran', 'hotdog', 'chipilones', 'taco', 'tortas', 'papancha', 'lorenza', 'taco', 'macho', 'burro', 'amazing', 'taco', 'n', 'sonoran', 'hotdog', 'lorenzas', 'de', 'asada', 'favorite', 'toasted', 'tortilla', 'asada', 'melted', 'cheese', 'salsa', 'truly', 'recommend', 'cheke', 'mexican', 'food', 'everyone', 'delicious', 'pork', 'taco', 'quesadilla', 'chicken', 'burrito', 'awesome', 'great', 'customer', 'service', 'friendly', 'food', 'really', 'good', 'real', 'mexican', 'food', 'like', 'cafeteria', 'food', 'guadalajara', 'grill', 'ole', 'service', 'okay', 'expect', 'food', 'truck', 'sometimes', 'wait', 'obnoxious', 'salsa', 'selection', 'good', 'wish', 'used', 'real', 'mexican', 'corn', 'tortilla', 'thick', 'yellow', 'one', 'maybe', 'future', 'couple', 'carne', 'asada', 'taco', 'hotdog', 'pretty', 'good', 'seem', 'like', 'lot', 'food', 'place', 'one', 'place', 'go', 'taco', 'burrito', 'tucson', 'yes', 'cost', 'drive', 'thru', 'picky', 'food', 'promise', 'regret', 'burro', 'taco', 'extremely', 'fresh', 'salsa', 'bar', 'delightful', 'staff', 'closed', 'sunday', 'monday', 'tried', 'place', 'first', 'time', 'taco', 'amazing', 'really', 'good', 'quality', 'meat', 'taco', 'bar', 'clean', 'kid', 'even', 'loved', 'taco', 'son', 'ate', 'back', 'sure', 'probably', 'one', 'new', 'go', 'abodaba', 'absolute', 'best', 'ever', 'spice', 'perfect', 'moist', 'flavorful', 'lorenza', 'toasted', 'street', 'taco', 'caramello', 'delicious', 'corn', 'tortilla', 'lorenza', 'toasted', 'perfectly', 'chipilon', 'style', 'sonoran', 'dog', 'good', 'star', 'dish', 'service', 'friendly', 'last', 'night', 'one', 'brother', 'business', 'saw', 'daughter', 'purse', 'table', 'party', 'three', 'came', 'got', 'chair', 'another', 'table', 'put', 'end', 'table', 'put', 'purse', 'sweet', 'today', 'went', 'see', 'daughter', 'work', 'asked', 'plan', 'got', 'replied', 'going', 'go', 'eat', 'asked', 'replied', 'back', 'taco', 'place', 'laughed', 'said', 'thinking', 'day', 'good', 'hilarious', 'fact', 'abodaba', 'excellent', 'top', 'favorite', 'mind', 'blowing', 'good', 'definitely', 'return', 'go', 'way', 'go', 'worth', 'every', 'dime', 'money', 'outstanding', 'tucson', 'top', 'tier', 'element', 'quite', 'good', 'get', 'still', 'worthy', 'regular', 'business', 'good', 'experience', 'might', 'repeat', 'business', 'convenient', 'option', 'one', 'category', 'whim', 'would', 'among', 'first', 'thing', 'come', 'mind', 'would', 'definitely', 'recommend', 'trying', 'get', 'take', 'good', 'would', 'recommend', 'waste', 'money', 'still', 'business', 'stay', 'away', 'cost', 'adobado', 'taco', 'excellent', 'sonoran', 'dog', 'good', 'well', 'love', 'salsa', 'bar', 'spicier', 'salsa', 'make', 'eye', 'water', 'heat', 'spice', 'lover', 'joy', 'guy', 'great', 'job', 'adobo', 'taco', 'favorite', 'tucson', 'standard', 'sonoran', 'hot', 'dog', 'wrong', 'easy', 'access', 'river', 'good', 'food', 'costumer', 'service', 'trash', 'bad', 'vibe', 'rather', 'drive', 'extra', 'mile', 'bk', 'taco', 'food', 'good', 'order', 'hot', 'dog', 'taco', 'de', 'carne', 'asada', 'red', 'salsa', 'super', 'good', 'specially', 'love', 'spicy', 'food', 'overall', 'customer', 'service', 'bit', 'guy', 'got', 'order', 'seem', 'mad', 'welcoming', 'guest', 'review', 'mention', 'expensive', 'place', 'taco', 'burrito', 'spot', 'taco', 'burrito', 'small', 'best', 'special', 'flavor', 'wise', 'might', 'underwhelming', 'priced', 'taco', 'spot', 'ever', 'love', 'place', 'sonoran', 'hotdog', 'leave', 'slot', 'desired', 'rest', 'food', 'amazing', 'el', 'cheke', 'opened', 'tucson', 'mall', 'recently', 'thankful', 'new', 'awesome', 'place', 'get', 'authentic', 'mexican', 'food', 'side', 'town', 'pork', 'taco', 'steak', 'taco', 'sonoran', 'dog', 'sonoran', 'dog', 'usual', 'topping', 'perfectly', 'executed', 'taco', 'well', 'seasoned', 'meat', 'perfect', 'amount', 'char', 'great', 'meat', 'tortilla', 'ratio', 'well', 'condiment', 'bar', 'fully', 'stocked', 'usual', 'extra', 'complete', 'meal', 'got', 'taco', 'hotdog', 'definitely', 'steal', 'service', 'also', 'friendly', 'fast', 'definitely', 'back', 'try', 'item']
5 -> (Document: 729) -> Score: 0.33

## 4 - Query Expansion
- Expand the query using embeddings
- Also Testing using Wordnet for synonyms since my dataset is small
- Goal: Create a function with both and test results later

In [ ]:
# use sentence transformer model
model_s = SentenceTransformer('all-MiniLM-L6-v2')
# Retrieve index tokens and embedded the vocabulary
vocab = list(invert_index.keys())
embeddings = model_s.encode(vocab)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [150]:
#Query expansion func
def query_expand(query):
    #tokenize query
    # q_tokens = query.lower().split()
    q_tokens = preprocessv2(query)
    # print(q_tokens)

    #embedding for query
    query_embeddings = model_s.encode(query)

    #dot product vocab * query embeddings
    prod = cosine_similarity([query_embeddings],embeddings)[0]
    top = np.argsort(prod)[-3:][::-1]
    # expansion.extend([vocab[i] for i in top if vocab[i] not in q_tokens])
    expansion = [vocab[i] for i in top if vocab[i] not in q_tokens]
    return q_tokens + expansion

In [151]:
# Testing query expansion via embedding OUTPUT -> new query
query_expand('What are the best vegan taco shops?')

['best', 'vegan', 'taco', 'shop', 'taquitos', 'tacobell']

Now lets test wordnet for synonym based query expansion

In [95]:
#Wordnet Synonym expansion
def syn_expand(query):
    # query = query.lower().split() #basic tokenization
    q_tokens = preprocessv2(query) #consistent approach
    # print(q_tokens)
    #Set - for unique values
    expanded = set(q_tokens)

    for word in q_tokens:
        syn = wordnet.synsets(word)

        for syns in syn[:2]: #2 synonym limit
            for lemma in syns.lemmas():
                expanded.add(lemma.name().replace("_", " "))
    
    return list(expanded)

In [136]:
syn_expand('What are the best vegan shops?') #taco was bad

['best', 'workshop', 'shop', 'vegan', 'topper', 'store']

Okay lets not use synonym based expansion that was unexpected

## 5 - Semantic Embedding Similarity

In [65]:
doc_embeds = model_s.encode(documents, show_progress_bar=True)

Batches:   0%|          | 0/31 [00:00<?, ?it/s]

In [186]:
#Semantic Search Func
def semantic_search(query):

    # preprocess query using preprocessv2
    q_tokens = preprocessv2(query)

    #Query Expansion
    exp_tokens = query_expand(query)

    extra_tokens = [x for x in exp_tokens if x not in q_tokens] # just new query words that were added in the expansion of the query
    exp_text = " ".join(q_tokens + extra_tokens)

    
    # vector = model_s.encode(query)
    vector = model_s.encode(exp_text)


    similarity = cosine_similarity([vector],doc_embeds)[0]

    top_doc = np.argsort(similarity)[-10:][::-1] #top 10 ordered descending

    for x in range(10):
        doc_id = top_doc[x]
        score = similarity[doc_id]
        print(f'Score: {score:.2f} --> {tokens[doc_id]}')
    return top_doc

In [187]:
semantic_search('What are the best vegan taco shops?')

Score: 0.67 --> ['name', 'la', 'chaiteria', 'category', 'mexican', 'taco', 'vegan', 'vegetarian', 'food', 'truck', 'food', 'restaurant', 'rating', 'review', 'hungry', 'friday', 'afternoon', 'lunch', 'looking', 'restaurant', 'driving', 'saw', 'new', 'place', 'dropped', 'ordered', 'al', 'pastor', 'taco', 'raja', 'taco', 'green', 'chile', 'mushrooom', 'cream', 'al', 'pastor', 'taste', 'authentic', 'oily', 'raja', 'tasteless', 'bland', 'horrible', 'wow', 'either', 'another', 'note', 'place', 'clean', 'tidy', 'stopped', 'today', 'pick', 'large', 'order', 'family', 'taco', 'night', 'everything', 'tasted', 'incredible', 'fresh', 'ordered', 'taco', 'al', 'pastor', 'mole', 'taco', 'definitely', 'back', 'happy', 'wendy', 'opened', 'cafe', 'closer', 'neck', 'wood', 'great', 'menu', 'item', 'featuring', 'best', 'vegetarian', 'food', 'cafe', 'vegetarian', 'love', 'magic', 'food', 'wendy', 'creates', 'potato', 'filled', 'taco', 'jackfruit', 'carnitas', 'go', 'wrong', 'happen', 'day', 'cashew', 'based', 'alfredo', 'gluten', 'free', 'pasta', 'menu', 'whoa', 'tastebud', 'love', 'forever', 'yessss', 'la', 'chaiteria', 'vegan', 'menu', 'regular', 'menu', 'also', 'make', 'vegan', 'dish', 'vegetarian', 'adding', 'cheese', 'jackfruit', 'flavorful', 'recommend', 'house', 'drink', 'orchata', 'good', 'turmeric', 'lemonade', 'jamaica', 'also', 'great', 'portion', 'big', 'food', 'worth', 'every', 'penny', 'staff', 'super', 'friendly', 'attentive', 'want', 'ensure', 'great', 'experience', 'big', 'fan', 'tumerico', 'spot', 'happy', 'location', 'tucson', 'saffron', 'latte', 'espresso', 'mesquite', 'latte', 'ropa', 'vieja', 'raja', 'taco', 'place', 'amazing', 'portion', 'good', 'size', 'taste', 'quality', 'ingredient', 'created', 'fun', 'artistic', 'space', 'enjoy', 'new', 'favorite', 'restaurant', 'amazing', 'customer', 'service', 'fast', 'service', 'best', 'food', 'tucson', 'place', 'amazing', 'compared', 'one', 'owned', 'company', 'one', 'feel', 'bigger', 'portion', 'needed', 'great', 'side', 'town', 'plus', 'much', 'closer', 'seeing', 'lost', 'vegan', 'burrito', 'side', 'town', 'definitely', 'make', 'definitely', 'would', 'recommend', 'al', 'pastor', 'taco', 'little', 'spicy', 'make', 'even', 'spicier', 'salsa', 'make', 'salsa', 'amazing', 'tad', 'pricey', 'side', 'compared', 'regular', 'mexican', 'food', 'place', 'around', 'vegan', 'healthy', 'non', 'vegan', 'mexican', 'food', 'right', 'point', 'price', 'come', 'disappointed', 'place', 'point', 'vegan', 'non', 'vegan', 'option', 'staff', 'absolutely', 'amazing', 'kind', 'helpful', 'create', 'fantastic', 'atmosphere', 'food', 'delicious', 'worth', 'try', 'normally', 'amazing', 'place', 'however', 'get', 'cuban', 'jackfruit', 'today', 'tried', 'jackfruit', 'pineapple', 'say', 'stream', 'taco', 'tiny', 'bit', 'jackfruit', 'sour', 'pineapple', 'cutting', 'sorry', 'next', 'time', 'stick', 'like', 'carne', 'con', 'chili', 'burro', 'one', 'best', 'rice', 'bean', 'also', 'really', 'good', 'miss', 'spot', 'best', 'vegan', 'mexican', 'food', 'town', 'support', 'local', 'woman', 'owner', 'finally', 'got', 'check', 'spinoff', 'tumerico', 'location', 'also', 'cute', 'little', 'market', 'food', 'snack', 'beverage', 'toiletry', 'desert', 'go', 'food', 'truck', 'outside', 'meat', 'dish', 'make', 'friendlier', 'wider', 'base', 'people', 'inside', 'vegan', 'vegetarian', 'menu', 'always', 'changing', 'always', 'go', 'tostados', 'yummy', 'combination', 'crunchy', 'savory', 'flavorful', 'bean', 'well', 'cooked', 'seasoned', 'food', 'tends', 'bit', 'oily', 'downside', 'also', 'tried', 'one', 'juice', 'pricy', 'healthy', 'balance', 'veggie', 'fruit', 'citrus', 'another', 'reason', 'check', 'place', 'amazing', 'mural', 'artwork', 'tucson', 'must', 'see', 'great', 'addition', 'tumerico', 'family', 'much', 'needed', 'boost', 'vegan', 'community', 'went', 'friend', 'try', 'something', 'new', 'liked', 'cafe', 'restaurant', 'going', 'coffee', 'good', 'got', 'horchata', 'latte', 'hot', 'lacking', 'flavor', 'cup', 'steaming', 'hot', 'coffee', 'lukewarm', 'meal', 'customer', 'got', 'look', 'great', 'though', 'also', 'friend', 'liked', 'mole', 'latte', 'complaint', 'latte', 'come', 'soy', 'milk', 'fantastic', 'place', 'vegan', 'meat', 'dish', 'bad', 'meal', 'time', 'went', 'hear', 'coffee', 'good', 'go', 'food', 'give', 'shot', 'glad', 'west', 'side', 'town', 'west', 'side', 'getting', 'great', 'addition', 'different', 'tumerico', 'great', 'salsa', 'bar', 'instead', 'salsa', 'topping', 'already', 'appearing', 'plate', 'great', 'drink', 'menu', 'coffee', 'mexican', 'drink', 'vegetarian', 'food', 'menu', 'fantastic', 'original', 'tumerico', 'store', 'buy', 'burrito', 'salsa', 'tamale', 'find', 'quince', 'homemade', 'chip', 'much', 'pandemic', 'also', 'offering', 'toilet', 'paper', 'hand', 'sanitizer', 'etc', 'whole', 'staff', 'friendly', 'feel', 'like', 'home', 'delicious', 'fresh', 'coffee', 'friendly', 'staff', 'added', 'meat', 'friendly', 'food', 'truck', 'able', 'serve', 'selection', 'guest', 'also', 'great', 'store', 'selection', 'bottled', 'drink', 'absolutely', 'love', 'getting', 'freshly', 'cut', 'coconut', 'everytime', 'stop', 'first', 'time', 'trying', 'place', 'got', 'takeout', 'called', 'order', 'staff', 'nice', 'cuban', 'burro', 'side', 'rice', 'bean', 'veggie', 'filling', 'delicious', 'definitely', 'go', 'back', 'try', 'food', 'absolutely', 'love', 'good', 'drink', 'staff', 'everyone', 'respectful', 'energy', 'welcoming', 'never', 'disappointed', 'coming', 'absolutely', 'love', 'absolutely', 'love', 'restaurant', 'gem', 'side', 'town', 'dish', 'packed', 'flavor', 'every', 'bite', 'portion', 'generous', 'price', 'fair', 'also', 'love', 'refrigerator', 'full', 'awesome', 'dessert', 'refreshing', 'drink', 'kombucha', 'tap', 'get', 'started', 'salsa', 'bar', 'gosh', 'welcoming', 'wonderful', 'restaurant', 'loyal', 'devotee', 'tumerico', 'someone', 'explained', 'u', 'la', 'chaiteria', 'tumerico', 'sister', 'restaurant', 'make', 'trip', 'lot', 'similar', 'vegan', 'option', 'find', 'tumerico', 'husband', 'delighted', 'find', 'la', 'chaiteria', 'option', 'meat', 'eater', 'omnivore', 'generally', 'enchilada', 'chile', 'relleno', 'delicious', 'portion', 'size', 'large', 'ended', 'taking', 'part', 'meal', 'home', 'got', 'full', 'finish', 'tried', 'turmeric', 'lemonade', 'delighted', 'good', 'tasted', 'staff', 'much', 'like', 'staff', 'tumerico', 'delightful', 'food', 'came', 'quickly', 'la', 'chaiteria', 'applying', 'liquor', 'license', 'sell', 'beer', 'wine', 'think', 'place', 'get', 'better', 'thought', 'adding', 'adult', 'beverage', 'meal', 'sound', 'even', 'amazing', 'folk', 'complained', 'thing', 'oily', 'experience', 'either', 'tumerico', 'folk', 'also', 'complained', 'price', 'la', 'chaiteria', 'source', 'majority', 'ingredient', 'organic', 'food', 'supply', 'organic', 'food', 'cost', 'money', 'also', 'think', 'quality', 'ingredient', 'reflected', 'taste', 'food', 'looking', 'fabulous', 'southwestern', 'food', 'la', 'chaiteria']
Score: 0.63 --> ['name', 'taco', 'shop', 'company', 'category', 'restaurant', 'fast', 'food', 'mexican', 'rating', 'review', 'good', 'fast', 'inexpensive', 'like', 'get', 'veggie', 'burrito', 'husband', 'love', 'bacon', 'egg', 'cheese', 'burrito', 'available', 'time', 'breakfast', 'place', 'ambiance', 'get', 'go', 'happy', 'got', 'carne', 'asada', 'burrito', 'avocado', 'used', 'fresh', 'significantly', 'took', 'away', 'ingredient', 'finish', 'whole', 'thing', 'could', 'sure', 'see', 'visit', 'place', 'bar', 'taco', 'shop', 'pretty', 'decent', 'place', 'late', 'night', 'l', 'always', 'get', 'rolled', 'taquitos', 'always', 'satisfies', 'good', 'food', 'especially', 'drunk', 'overall', 'complain', 'pretty', 'good', 'tasting', 'taco', 'spot', 'driving', 'city', 'happened', 'upon', 'taco', 'shop', 'great', 'fish', 'taco', 'shrimp', 'burrito', 'great', 'price', 'tiny', 'spot', 'serf', 'yummy', 'authentic', 'dish', 'counter', 'taco', 'shop', 'tried', 'carnitas', 'unimpressed', 'pork', 'lean', 'flavorless', 'dry', 'side', 'tried', 'carne', 'asada', 'similarly', 'unimpressed', 'meat', 'similarly', 'flavorless', 'bit', 'salty', 'side', 'sure', 'think', 'might', 'detected', 'hint', 'pork', 'somewhere', 'eat', 'pig', 'might', 'want', 'ask', 'hearing', 'friend', 'rave', 'place', 'decided', 'give', 'another', 'shot', 'actually', 'really', 'glad', 'star', 'show', 'al', 'pastor', 'burrito', 'marinated', 'pork', 'tender', 'full', 'flavor', 'ingredient', 'presented', 'perfect', 'proportion', 'even', 'put', 'fresh', 'chopped', 'cilantro', 'really', 'set', 'burrito', 'apart', 'al', 'pastor', 'saucy', 'accustomed', 'work', 'really', 'well', 'dare', 'say', 'tastiest', 'al', 'pastor', 'part', 'town', 'favor', 'try', 'also', 'delicious', 'green', 'chili', 'burrito', 'pork', 'reasonably', 'good', 'really', 'make', 'awesome', 'douse', 'entire', 'burrito', 'heavy', 'helping', 'green', 'chili', 'sauce', 'cheese', 'lettuce', 'call', 'wet', 'style', 'call', 'yummy', 'slightly', 'putting', 'though', 'practice', 'sticking', 'burrito', 'microwave', 'styrofoam', 'container', 'melt', 'cheese', 'polystyrene', 'supposedly', 'microwave', 'safe', 'probably', 'like', 'clearly', 'systematically', 'jeopardizing', 'customer', 'health', 'still', 'took', 'notice', 'ordered', 'less', 'exciting', 'red', 'chili', 'burrito', 'thing', 'guess', 'wet', 'style', 'thing', 'microwaving', 'styrofoam', 'make', 'uncomfortable', 'probably', 'stay', 'away', 'wet', 'style', 'offering', 'aside', 'menu', 'item', 'neither', 'blown', 'away', 'disgusted', 'anything', 'tried', 'taco', 'shop', 'two', 'thing', 'really', 'delicious', 'would', 'still', 'probably', 'recommend', 'staying', 'away', 'carne', 'asada', 'carnitas', 'overall', 'converted', 'taco', 'shop', 'quite', 'alright', 'super', 'basic', 'eatery', 'three', 'watery', 'anemic', 'salsa', 'salsa', 'bar', 'guac', 'thin', 'seems', 'like', 'come', 'pourable', 'vessel', 'chunk', 'resembling', 'avocado', 'tomato', 'onion', 'etc', 'chicken', 'taco', 'meat', 'little', 'hard', 'tough', 'nugget', 'tasted', 'like', 'meat', 'sat', 'day', 'warmer', 'several', 'ua', 'student', 'place', 'quite', 'old', 'decrepit', 'run', 'big', 'hole', 'plaster', 'wall', 'booth', 'sat', 'appears', 'clean', 'need', 'overhaul', 'friendly', 'clerk', 'town', 'many', 'stellar', 'place', 'get', 'taco', 'would', 'return', 'one', 'meh', 'maybe', 'serious', 'need', 'food', 'night', 'looking', 'really', 'luscious', 'fresh', 'quality', 'taco', 'gone', 'way', 'time', 'care', 'admit', 'let', 'face', 'cheese', 'quesadilla', 'go', 'perfect', 'time', 'day', 'taste', 'amazing', 'used', 'live', 'street', 'right', 'behind', 'shop', 'heart', 'broken', 'move', 'away', 'nothing', 'better', 'cab', 'driver', 'drop', 'friday', 'night', 'walking', 'home', 'ultimate', 'prize', 'cheese', 'quesadilla', 'horchata', 'extra', 'lime', 'place', 'eat', 'late', 'night', 'business', 'name', 'suggests', 'go', 'want', 'drunken', 'taco', 'get', 'fried', 'fish', 'real', 'good', 'carne', 'asada', 'recommend', 'burrito', 'best', 'value', 'cheaper', 'betos', 'nicos', 'better', 'quality', 'biggest', 'gripe', 'place', 'wait', 'weekend', 'night', 'ridiculous', 'get', 'steak', 'egg', 'burrito', 'breakfast', 'shrimp', 'burrito', 'lunch', 'able', 'try', 'anything', 'else', 'b', 'c', 'two', 'good', 'expect', 'ambience', 'stellar', 'service', 'good', 'food', 'delicious', 'burrito', 'really', 'set', 'establishment', 'apart', 'hour', 'taco', 'stand', 'salsa', 'delicious', 'load', 'much', 'please', 'use', 'meal', 'home', 'truly', 'hit', 'spot', 'especially', 'late', 'night', 'arizona', 'burrito', 'delicious', 'one', 'best', 'burrito', 'ever', 'definitely', 'satisfied', 'okay', 'little', 'confused', 'place', 'little', 'star', 'think', 'deserves', 'fine', 'dining', 'going', 'impress', 'date', 'well', 'lived', 'close', 'location', 'month', 'love', 'late', 'night', 'run', 'quick', 'lunch', 'greasy', 'mexican', 'fast', 'food', 'found', 'general', 'menu', 'item', 'consistently', 'good', 'affordable', 'think', 'veggie', 'burrito', 'california', 'breakfast', 'burrito', 'outstanding', 'thing', 'order', 'like', 'chicken', 'burrito', 'maybe', 'felt', 'like', 'something', 'chicken', 'guac', 'salsa', 'bar', 'job', 'small', 'shop', 'nice', 'cool', 'employee', 'efficient', 'rarely', 'wait', 'minute', 'get', 'food', 'even', 'packed', 'full', 'drunk', 'college', 'kid', 'salsa', 'tasteless', 'meat', 'could', 'use', 'salt', 'spice', 'fish', 'taco', 'good', 'bad', 'salsa', 'elevate', 'let', 'honest', 'else', 'gonna', 'eat', 'around', 'area', 'morning', 'restaurant', 'fabulous', 'food', 'satisfying', 'healthy', 'reasonably', 'priced', 'come', 'one', 'come', 'glad', 'delicious', 'food', 'gotta', 'love', 'big', 'burrito', 'good', 'price', 'clean', 'place', 'open', 'favorite', 'place', 'get', 'late', 'night', 'burrito', 'college', 'whenever', 'back', 'town', 'visit', 'stop', 'clarify', 'thing', 'ua', 'session', 'break', 'cut', 'midnight', 'ish', 'taco', 'shop', 'awesome', 'time', 'never', 'satisfied', 'taste', 'food', 'open', 'hour', 'thing', 'would', 'advice', 'go', 'night', 'prepared', 'deal', 'sketch', 'situation', 'like', 'people', 'fighting', 'seen', 'also', 'made', 'interesting', 'taco', 'shop', 'win', 'great', 'food', 'lot', 'various', 'great', 'eats', 'open', 'best', 'quick', 'dirty', 'mexican', 'food', 'tucson', 'far', 'better', 'nico', 'mexican', 'fast', 'food', 'excellent', 'food', 'great', 'tasting', 'homemade', 'salsa', 'various', 'level', 'picante', 'service', 'always', 'friendly', 'fast', 'nothing', 'ever', 'ordered', 'greasy', 'overlooked', 'favorite', 'chicken', 'fajitas', 'burrito', 'amazing', 'flavor', 'also', 'customize', 'breakfast', 'burrito', 'order', 'hesitate', 'make', 'way', 'want', 'open', 'always', 'delicious', 'portion', 'plentiful', 'sabroso', 'one', 'thing', 'see', 'take', 'eat', 'dining', 'several', 'small', 'table', 'got', 'group', 'room', 'order', 'home', 'cooked', 'tasting', 'food', 'dine', 'home', 'well', 'worth', 'checking', 'one', 'regular', 'spot']

array([751, 549, 361, 715,  43, 730, 709, 647, 318, 842], dtype=int64)

## 6 - Hybrid Scoring Approach
- Combine both BM25 Results with Semantic Searching with a split % between their scores
- GOAL: To achieve a moderate output based off the strenghts of both methods

In [228]:
def hybrid_search(query,a =.2):

    # preprocess query using preprocessv2
    q_tokens = preprocessv2(query)

    #Query Expansion
    exp_tokens = query_expand(query)

    extra_tokens = [x for x in exp_tokens if x not in q_tokens] # just new query words that were added in the expansion of the query
    exp_text = " ".join(q_tokens + extra_tokens)

    # print(extra_tokens)
    print(f'Query: {exp_text}')

    #BM25 Scoring - weight original query strongest followed by little of expansion
    bm25_scoring = (
        1*np.array(bm25.get_scores(q_tokens)) +  .3*np.array(bm25.get_scores(extra_tokens))
    )

    #Semantic Scoring
    vector = model_s.encode(exp_text)
    semantic_scoring = cosine_similarity([vector],doc_embeds)[0]

    #Combination
    final = a*np.array(bm25_scoring) + (1-a) * semantic_scoring

    top_documents = np.argsort(final)[-10:][::-1]
    for x in range(10):
        doc_id = top_documents[x]
        score = final[doc_id]
        print(f'Score: {score:.2f} --> {tokens[doc_id]}')

    return top_documents

In [229]:
hybrid_search('What are the best vegan taco shops?')

Query: best vegan taco shop taquitos tacobell
Score: 2.66 --> ['name', 'taco', 'stop', 'category', 'caterer', 'event', 'planning', 'service', 'food', 'truck', 'food', 'restaurant', 'mexican', 'rating', 'review', 'excellent', 'taco', 'price', 'reasonable', 'quality', 'quantity', 'received', 'hope', 'around', 'next', 'visit', 'tuscon', 'wanted', 'know', 'hype', 'tried', 'jackfruit', 'burro', 'mind', 'vegan', 'vegetarian', 'wanted', 'try', 'also', 'actually', 'hate', 'jackfruit', 'asian', 'family', 'think', 'love', 'big', 'fan', 'kind', 'fruit', 'durian', 'jackfruit', 'lychee', 'etc', 'think', 'eating', 'jackfruit', 'burro', 'long', 'long', 'time', 'marinaded', 'something', 'good', 'felt', 'like', 'best', 'burro', 'far', 'life', 'soooo', 'big', 'usually', 'never', 'finish', 'one', 'whole', 'burro', 'size', 'one', 'sitting', 'ate', 'put', 'good', 'mood', 'texted', 'sister', 'florida', 'good', 'service', 'great', 'super', 'friendly', 'food', 'fresh', 'made', 'order', 'glad', 'moved', 'would', 'never', 'experienced', 'today', 'stopped', 'little', 'food', 'truck', 'cause', 'obviously', 'hungry', 'typical', 'mexican', 'food', 'menu', 'noticed', 'bacon', 'wrapped', 'burro', 'decided', 'give', 'try', 'ground', 'beef', 'holy', 'f', 'k', 'one', 'best', 'damn', 'burrito', 'ever', 'hard', 'impress', 'mexican', 'food', 'day', 'even', 'wanna', 'right', 'review', 'keep', 'gem', 'secret', 'community', 'disservice', 'food', 'take', 'time', 'cook', 'rushing', 'sweet', 'little', 'old', 'abuela', 'cause', 'back', 'cooking', 'love', 'thanks', 'taco', 'stop', 'making', 'today', 'great', 'day', 'treat', 'east', 'side', 'tucson', 'two', 'sonoran', 'hot', 'dog', 'veg', 'meat', 'one', 'flavorful', 'jackfruit', 'birria', 'available', 'taco', 'burrito', 'taco', 'absolutely', 'delicious', 'best', 'prepared', 'jackfruit', 'ever', 'wish', 'ordered', 'plenty', 'vegan', 'option', 'available', 'looking', 'new', 'delicious', 'food', 'side', 'town', 'keto', 'burrito', 'amazing', 'net', 'carb', 'delicious', 'meat', 'better', 'food', 'truck', 'keto', 'friendly', 'really', 'excited', 'try', 'taco', 'stop', 'little', 'hard', 'get', 'time', 'actually', 'open', 'supposedly', 'open', 'monday', 'friday', 'time', 'hour', 'truck', 'actually', 'closed', 'today', 'ordered', 'jackfruit', 'taco', 'carne', 'asada', 'burrito', 'sonoran', 'hotdog', 'place', 'tucson', 'serve', 'jackfruit', 'vegetarian', 'vegan', 'option', 'stoked', 'actually', 'unfortunately', 'big', 'fan', 'spice', 'used', 'jackfruit', 'seemed', 'overpowering', 'probably', 'much', 'chili', 'powder', 'whatever', 'spice', 'probably', 'overpowering', 'accentuated', 'sweet', 'salsa', 'crema', 'taco', 'came', 'flour', 'tortilla', 'spiced', 'jackfruit', 'pico', 'de', 'gallo', 'avocado', 'slice', 'side', 'rice', 'bean', 'carne', 'asada', 'best', 'either', 'thought', 'bit', 'strange', 'came', 'cabbage', 'cheese', 'bean', 'hoping', 'really', 'good', 'work', 'though', 'help', 'meat', 'grilled', 'super', 'good', 'however', 'sonoran', 'hotdog', 'save', 'meal', 'although', 'bit', 'burnt', 'outside', 'fixing', 'everything', 'right', 'really', 'would', 'love', 'give', 'star', 'place', 'really', 'hoping', 'improvement', 'next', 'time', 'also', 'today', 'birria', 'would', 'great', 'try', 'next', 'time', 'well', 'anyways', 'take', 'taco', 'stop', 'hopefully', 'people', 'try', 'food', 'give', 'feedback', 'could', 'try', 'see', 'work', 'ordered', 'two', 'jackfruit', 'burrito', 'three', 'bean', 'cheese', 'burrito', 'kid', 'stuffed', 'delicious', 'ingredient', 'toasted', 'outside', 'delicious', 'definitely', 'making', 'primary', 'east', 'side', 'burrito', 'place', 'found', 'taco', 'truck', 'heading', 'back', 'hotel', 'rating', 'looked', 'good', 'stopped', 'disappointed', 'apprehensive', 'first', 'basic', 'looking', 'truck', 'small', 'number', 'rating', 'however', 'carne', 'asada', 'burrito', 'chicken', 'quesadilla', 'burrito', 'big', 'good', 'size', 'meat', 'tasty', 'chicken', 'quesadilla', 'best', 'seasoned', 'perfection', 'would', 'go', 'back', 'would', 'given', 'five', 'star', 'price', 'touch', 'high', 'little', 'salty', 'although', 'like', 'salty', 'wish', 'could', 'given', 'four', 'half', 'star', 'taco', 'truck', 'amazing', 'everyone', 'family', 'got', 'something', 'different', 'loved', 'bit', 'wait', 'usually', 'one', 'two', 'lady', 'working', 'well', 'worth', 'wait', 'delicious', 'vegan', 'option', 'really', 'enjoyed', 'jackfruit', 'street', 'taco', 'option', 'everyone', 'great', 'costumer', 'service', 'best', 'quesa', 'birria', 'taco', 'town', 'absolutely', 'delicious', 'worth', 'wait', 'patient', 'good', 'thing', 'take', 'time', 'excellent', 'partial', 'beef', 'burrito', 'ambiance', 'would', 'something', 'would', 'expect', 'poor', 'dusty', 'town', 'northern', 'mexico', 'super', 'cheap', 'metal', 'folding', 'table', 'cheap', 'metal', 'really', 'cheap', 'folding', 'chair', 'set', 'rear', 'back', 'taco', 'truck', 'really', 'loud', 'generator', 'running', 'irritating', 'carne', 'asada', 'taco', 'dry', 'must', 'cooked', 'many', 'hour', 'let', 'dry', 'flour', 'tortilla', 'thin', 'lone', 'per', 'taco', 'broke', 'open', 'picked', 'usually', 'street', 'taco', 'like', 'tortilla', 'awful', 'threw', 'garbage', 'belonged', 'order', 'side', 'rice', 'bean', 'total', 'wast', 'money', 'good', 'part', 'really', 'love', 'jackfruit', 'burrito', 'would', 'buy', 'one', 'eat', 'girlfriend', 'love', 'amount', 'vegan', 'option', 'available', 'super', 'tasty', 'tell', 'vegan', 'quesadilla', 'apart', 'normal', 'one', 'good', 'thank', 'much', 'vegan', 'option', 'hand', 'best', 'mexican', 'vegan', 'place', 'town', 'favorite', 'humongous', 'jackfruit', 'burrito', 'delicious', 'filling', 'bean', 'rice', 'tasty', 'love', 'guy', 'use', 'cabbage', 'instead', 'lettuce', 'burrito', 'salsa', 'spot', 'creama', 'die', 'work', 'butt', 'truck', 'friendly', 'miss', 'taco', 'truck', 'stopped', 'visiting', 'mount', 'lemmon', 'everything', 'delicious', 'especially', 'loved', 'birria', 'taco', 'perfectly', 'crispy', 'shell', 'tortilla', 'seemed', 'really', 'fresh', 'meat', 'flavorful', 'right', 'amount', 'cheese', 'highly', 'recommend', 'lady', 'running', 'truck', 'one', 'rude', 'people', 'ever', 'dealt', 'spoke', 'slowly', 'think', 'knew', 'much', 'english', 'even', 'still', 'rude', 'short', 'answer', 'question', 'acted', 'like', 'bothering', 'literally', 'made', 'feel', 'like', 'terrible', 'human', 'treated', 'customer', 'like', 'gold', 'terrible', 'people', 'even', 'worth', 'food', 'service', 'bad', 'military', 'even', 'cadre', 'ruthless', 'omg', 'veteran', 'vegan', 'believe', 'great', 'ordered', 'jackfruit', 'vegan', 'burrito', 'little', 'buck', 'sooooo', 'worth', 'tasty', 'literally', 'hold', 'title', 'burrito', 'say', 'alot', 'happy', 'finally', 'went', 'actually', 'bumped', 'owner', 'maybe', 'idk', 'one', 'day', 'safeway', 'produce', 'saw', 'looking', 'vegan', 'food', 'told', 'taco', 'stop', 'thankful', 'good', 'back', 'prob', 'way', 'much', 'haha', 'awesome', 'taco', 'worker', 'masked', 'customer', 'required', 'masked', 'wait', 'go', 'back', 'asada', 'ground', 'beef', 'chicken', 'came', 'cabbage', 'tomato', 'onion', 'cilantro', 'salsa', 'side', 'great', 'eating', 'surprisingly', 'good', 'food', 'unimpressive', 'looking', 'food', 'truck', 'way', 'location', 'enjoyed', 'carne', 'asada', 'taco', 'quesadilla', 'couple', 'ice', 'cold', 'agua', 'frescas', 'back', 'location', 'moved', 'recently', 'jackfruit', 'alone', 'make', 'must', 'stop', 'food', 'truck', 'even', 'cupcake', 'super', 'slow', 'time', 'promise', 'worth', 'wait', 'new', 'food', 'truck', 'great', 'food', 'courteous', 'staff', 'great', 'location', 'east', 'side', 'atspeedway', 'houghton', 'must', 'try']
Score: 2.65 --> ['name', 'la', 'chaiteria', 'category', 'mexican', 'taco', 'vegan', 'vegetarian', 'food', 'truck', 'food', 'restaurant', 'rating', 'review', 'hungry', 'friday', 'afternoon', 'lunch', 'looking', 'restaurant', 'driving', 'saw', 'new', 'place', 'dropped', 'ordered', 'al', 'pastor', 'taco', 'raja', 'taco', 'green', 'chile', 'mushrooom', 'cream', 'al', 'pastor', 'taste', 'authentic', 'oily', 'raja', 'tasteless', 'bland', 'horrible', 'wow', 'either', 'another', 'note', 'place', 'clean', 'tidy', 'stopped', 'today', 'pick', 'large', 'order', 'family', 'taco', 'night', 'everything', 'tasted', 'incredible', 'fresh', 'ordered', 'taco', 'al', 'pastor', 'mole', 'taco', 'definitely', 'back', 'happy', 'wendy', 'opened', 'cafe', 'closer', 'neck', 'wood', 'great', 'menu', 'item', 'featuring', 'best', 'vegetarian', 'food', 'cafe', 'vegetarian', 'love', 'magic', 'food', 'wendy', 'creates', 'potato', 'filled', 'taco', 'jackfruit', 'carnitas', 'go', 'wrong', 'happen', 'day', 'cashew', 'based', 'alfredo', 'gluten', 'free', 'pasta', 'menu', 'whoa', 'tastebud', 'love', 'forever', 'yessss', 'la', 'chaiteria', 'vegan', 'menu', 'regular', 'menu', 'also', 'make', 'vegan', 'dish', 'vegetarian', 'adding', 'cheese', 'jackfruit', 'flavorful', 'recommend', 'house', 'drink', 'orchata', 'good', 'turmeric', 'lemonade', 'jamaica', 'also', 'great', 'portion', 'big', 'food', 'worth', 'every', 'penny', 'staff', 'super', 'friendly', 'attentive', 'want', 'ensure', 'great', 'experience', 'big', 'fan', 'tumerico', 'spot', 'happy', 'location', 'tucson', 'saffron', 'latte', 'espresso', 'mesquite', 'latte', 'ropa', 'vieja', 'raja', 'taco', 'place', 'amazing', 'portion', 'good', 'size', 'taste', 'quality', 'ingredient', 'created', 'fun', 'artistic', 'space', 'enjoy', 'new', 'favorite', 'restaurant', 'amazing', 'customer', 'service', 'fast', 'service', 'best', 'food', 'tucson', 'place', 'amazing', 'compared', 'one', 'owned', 'company', 'one', 'feel', 'bigger', 'portion', 'needed', 'great', 'side', 'town', 'plus', 'much', 'closer', 'seeing', 'lost', 'vegan', 'burrito', 'side', 'town', 'definitely', 'make', 'definitely', 'would', 'recommend', 'al', 'pastor', 'taco', 'little', 'spicy', 'make', 'even', 'spicier', 'salsa', 'make', 'salsa', 'amazing', 'tad', 'pricey', 'side', 'compared', 'regular', 'mexican', 'food', 'place', 'around', 'vegan', 'healthy', 'non', 'vegan', 'mexican', 'food', 'right', 'point', 'price', 'come', 'disappointed', 'place', 'point', 'vegan', 'non', 'vegan', 'option', 'staff', 'absolutely', 'amazing', 'kind', 'helpful', 'create', 'fantastic', 'atmosphere', 'food', 'delicious', 'worth', 'try', 'normally', 'amazing', 'place', 'however', 'get', 'cuban', 'jackfruit', 'today', 'tried', 'jackfruit', 'pineapple', 'say', 'stream', 'taco', 'tiny', 'bit', 'jackfruit', 'sour', 'pineapple', 'cutting', 'sorry', 'next', 'time', 'stick', 'like', 'carne', 'con', 'chili', 'burro', 'one', 'best', 'rice', 'bean', 'also', 'really', 'good', 'miss', 'spot', 'best', 'vegan', 'mexican', 'food', 'town', 'support', 'local', 'woman', 'owner', 'finally', 'got', 'check', 'spinoff', 'tumerico', 'location', 'also', 'cute', 'little', 'market', 'food', 'snack', 'beverage', 'toiletry', 'desert', 'go', 'food', 'truck', 'outside', 'meat', 'dish', 'make', 'friendlier', 'wider', 'base', 'people', 'inside', 'vegan', 'vegetarian', 'menu', 'always', 'changing', 'always', 'go', 'tostados', 'yummy', 'combination', 'crunchy', 'savory', 'flavorful', 'bean', 'well', 'cooked', 'seasoned', 'food', 'tends', 'bit', 'oily', 'downside', 'also', 'tried', 'one', 'juice', 'pricy', 'healthy', 'balance', 'veggie', 'fruit', 'citrus', 'another', 'reason', 'check', 'place', 'amazing', 'mural', 'artwork', 'tucson', 'must', 'see', 'great', 'addition', 'tumerico', 'family', 'much', 'needed', 'boost', 'vegan', 'community', 'went', 'friend', 'try', 'something', 'new', 'liked', 'cafe', 'restaurant', 'going', 'coffee', 'good', 'got', 'horchata', 'latte', 'hot', 'lacking', 'flavor', 'cup', 'steaming', 'hot', 'coffee', 'lukewarm', 'meal', 'customer', 'got', 'look', 'great', 'though', 'also', 'friend', 'liked', 'mole', 'latte', 'complaint', 'latte', 'come', 'soy', 'milk', 'fantastic', 'place', 'vegan', 'meat', 'dish', 'bad', 'meal', 'time', 'went', 'hear', 'coffee', 'good', 'go', 'food', 'give', 'shot', 'glad', 'west', 'side', 'town', 'west', 'side', 'getting', 'great', 'addition', 'different', 'tumerico', 'great', 'salsa', 'bar', 'instead', 'salsa', 'topping', 'already', 'appearing', 'plate', 'great', 'drink', 'menu', 'coffee', 'mexican', 'drink', 'vegetarian', 'food', 'menu', 'fantastic', 'original', 'tumerico', 'store', 'buy', 'burrito', 'salsa', 'tamale', 'find', 'quince', 'homemade', 'chip', 'much', 'pandemic', 'also', 'offering', 'toilet', 'paper', 'hand', 'sanitizer', 'etc', 'whole', 'staff', 'friendly', 'feel', 'like', 'home', 'delicious', 'fresh', 'coffee', 'friendly', 'staff', 'added', 'meat', 'friendly', 'food', 'truck', 'able', 'serve', 'selection', 'guest', 'also', 'great', 'store', 'selection', 'bottled', 'drink', 'absolutely', 'love', 'getting', 'freshly', 'cut', 'coconut', 'everytime', 'stop', 'first', 'time', 'trying', 'place', 'got', 'takeout', 'called', 'order', 'staff', 'nice', 'cuban', 'burro', 'side', 'rice', 'bean', 'veggie', 'filling', 'delicious', 'definitely', 'go', 'back', 'try', 'food', 'absolutely', 'love', 'good', 'drink', 'staff', 'everyone', 'respectful', 'energy', 'welcoming', 'never', 'disappointed', 'coming', 'absolutely', 'love', 'absolutely', 'love', 'restaurant', 'gem', 'side', 'town', 'dish', 'packed', 'flavor', 'every', 'bite', 'portion', 'generous', 'price', 'fair', 'also', 'love', 'refrigerator', 'full', 'awesome', 'dessert', 'refreshing', 'drink', 'kombucha', 'tap', 'get', 'started', 'salsa', 'bar', 'gosh', 'welcoming', 'wonderful', 'restaurant', 'loyal', 'devotee', 'tumerico', 'someone', 'explained', 'u', 'la', 'chaiteria', 'tumerico', 'sister', 'restaurant', 'make', 'trip', 'lot', 'similar', 'vegan', 'option', 'find', 'tumerico', 'husband', 'delighted', 'find', 'la', 'chaiteria', 'option', 'meat', 'eater', 'omnivore', 'generally', 'enchilada', 'chile', 'relleno', 'delicious', 'portion', 'size', 'large', 'ended', 'taking', 'part', 'meal', 'home', 'got', 'full', 'finish', 'tried', 'turmeric', 'lemonade', 'delighted', 'good', 'tasted', 'staff', 'much', 'like', 'staff', 'tumerico', 'delightful', 'food', 'came', 'quickly', 'la', 'chaiteria', 'applying', 'liquor', 'license', 'sell', 'beer', 'wine', 'think', 'place', 'get', 'better', 'thought', 'adding', 'adult', 'beverage', 'meal', 'sound', 'even', 'amazing', 'folk', 'complained', 'thing', 'oily', 'experience', 'either', 'tumerico', 'folk', 'also', 'complained', 'price', 'la', 'chaiteria', 'source', 'majority', 'ingredient', 'organic', 'food', 'supply', 'organic', 'food', 'cost', 'money', 'also', 'think', 'quality', 'ingredient', 'reflected', 'taste', 'food', 'looking', 'fabulous', 'southwestern', 'food', 'la', 'chaiteria']

array([361, 751, 820, 263, 284, 549, 883, 529, 318, 690], dtype=int64)

This appears to be the best approach so far based on the slight investigation I have done reading the reviews and comparing them to the query. 
Though some results are being overpowered by the word "vegan" allowing ice cream and cafes/bakeries to be on the top 10...